on: [push, pull_request]

name: Build from SVN

jobs:
  macos:
    name: MacOS
    runs-on: macos-latest
    env:
      PKG_CONFIG_PATH: /opt/X11/lib/pkgconfig
      R_CRAN_WEB: "https://cran.rstudio.com"
      CRAN_RSYNC: 'mirrors.nic.cz::CRAN'
      R_TEXI2DVICMD: emulation

    steps:
    - name: System dependencies
      run: |
        brew install gcc gettext gmp isl jpeg libmpc libpng mpfr pcre2 pkg-config readline xz texinfo wget
        echo "FC=/usr/local/opt/gcc/bin/gfortran" >> $GITHUB_ENV
        echo "/Library/TeX/texbin" >> $GITHUB_PATH
        echo "/usr/local/opt/texinfo/bin" >> $GITHUB_PATH

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 100

    - name: Prepare
      run: |
        sed -i.bak 's|$(GIT) svn info|./.github/workflows/svn-info.sh|' Makefile.in
        ./.github/workflows/wget-recommended.sh
        ./.github/workflows/svn-info.sh

    - name: Configure
      run: CC=clang ./configure --disable-java --without-cairo --without-tcltk --without-x --with-aqua --with-lapack --enable-R-shlib SED=/usr/bin/sed
      env:
        PDFLATEX: ${{github.workspace}}/.github/workflows/dummy

    - name: Build
      run: make
      env:
        PDFLATEX: ${{github.workspace}}/.github/workflows/dummy

    - name: Check
      run: make check-all
      env:
        PDFLATEX: ${{github.workspace}}/.github/workflows/dummy

    - name: Print failed tests
      if: failure()
      run: tail -n100 tests/*.fail
